spring:
  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 3600000ms
  redis:
    #host: 10.123.52.189
    host: 127.0.0.1
    port: 6379
    database: 5
    password: Rd^is*8
logging:
  level:
    root: info